### ISSUE TITLE
PHPUnit plugin is causing massive lag/freeze!

### ISSUE THREAD

**Issue by Ilyes512** [stuartherbert/sublime-phpunit#37]
I am using ST2 on OSX 10.9 (Macbook Air 2012) and I decided to use ST2 as my main editor of choice.

After installing the necessary plugins (wish PHPUnit was one of) I noticed that when I opened ST2 and I pressed CMD+shift+P (super+shift+p) I had to wait 10+ seconds before ST2 was done and could react on my input again.

I almost got crazy over not being able to find the cause of this. I found it after disabling all plugins and activating the plugins one by one until I reached PHPUnit.

I havent adjusted anything with the PHPUnit settings. I also not using PEAR, but composer with globally installed PHPUnit (~/.composer/vendor/bin).

Anyone have the same experience? What could it be and how could this be solved?

**Comment by stuartherbert** [comment]
The lag is caused by the plugin searching for the phpunit.xml[.dist] file.

I've just pushed a couple of fixes that should speed this up a lot.

- Use the top_folder_hints to more accurately work out where the project's top-level folder is
- Improve the top_folder_hints list
- Use the folder_exclusions list to avoid searching folders
- Improve the folder_exclusions list to avoid searching the .git folder (which can be massive)

Hopefully this will resolve your issues. Please let me know if you're still having massive lag after updating to the latest version of the plugin.
