### ISSUE TITLE
PHPUnit doesn't show any results

### ISSUE THREAD

**Issue by nazieb** [stuartherbert/sublime-phpunit#41]
Hello, I'm using ST2 on OSX 10.9.2.

After I wrote my tests and the phpunit.xml, and "Run Tests..." from right-click menu, the console log appears in the bottom and shows the phpunit command but not the results.

When I copy the command and paste it on the Terminal, it works fine. What possibly did I do wrong? Because when I click "Open Class Being Tested" and "Open phpunit.xml" they just works well.

Here's the screenshot of the console:

![screen shot 2014-03-18 at 18 10 38](https://f.cloud.github.com/assets/463775/2446943/2da04cd2-ae8e-11e3-8960-d6be993c7ee7.png)

Sorry for bad English

**Comment by stuartherbert** [comment]
I've just added support for checking for vendor/bin/phpunit, and using that copy of phpunit if it exists. Hopefully that will fix this for you :)

**Comment by eko3alpha** [comment]
I was not able to get this PHPUnit plugin working without a third party plugin on OSX  ([Fix Mac Path](https://github.com/int3h/SublimeFixMacPath)).  Here is what I tried first.

OSX 10.11.4 (El  Capitan)
Sublime Text 3
PHPUnit plugin via package manager
PHPUnit global install via composer

I'm still getting the following error in the Sublime Text console when I try to run a test

```
/bin/sh: phpunit: command not found
```

I have phpunit installed via composer globally

```
$ ls ~/.composer/vendor/bin/
phpunit
```

However it's still not recognizing the globally installed phpunit install.  I see that the plugin has been updated to account for this location.  However it does not appear to be working.

```
>>> import os
>>> os.environ['PATH']
'/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin'
```

In order to get this PHPUnit plugin working I had to follow the instructions here for ST3
FixMacPath: https://github.com/int3h/SublimeFixMacPath

After the FixMacPath install and adding the "~/.composer/vendor/bin" directory PHPUnit now works.

```
>>> import os
>>> os.environ['PATH']
'~/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
```
